server:
  port: 8080
spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/play_dev?
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    thymeleaf:
      cache: false
      prefix: file:src/main/resources/templates/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: rhkddhks12@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope: profile_nickname, profile_image
            client-id: a7dbb3e5eda558e2c6b0b0a107bb4842
            client-secret: G3lLBF8NLjdR9BOleYMVxB8cUXimwvj4
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  site:
    baseUrl: http://localhost:8080
multipart:
  max-file-size: 10MB
  max-request-size: 10MB
  profile-images.location: src/main/resources/static/profile-images
  enabled: true
