spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: a7dbb3e5eda558e2c6b0b0a107bb4842
  mail:
    password:
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
